### ISSUE TITLE
Firefox 83 Issues with crashing tabs on PRoot

### ISSUE THREAD

**Issue by WMCB-Tech** [termux/proot#139]
Hello, recently i installed the latest version Firefox and it seems there's a bug with it,

Webpages keeps crashing at this point:
![Screenshot_2020-12-07-18-01-18-78_00dcaf2fcbe692c602a0957f19a66664.jpg](https://user-images.githubusercontent.com/65075766/101452859-5b3ce980-3969-11eb-9030-c68e56628c13.jpg)

Tried with/without sysvipc enabled but this error still persists,

I don't know if this is proot-related bug or not

**Comment by xeffyr** [comment]
Start firefox from terminal and see if some errors were printed.

**Comment by WMCB-Tech** [comment]
@xeffyr It seems it reports about fonts:
https://pastebin.com/8Ltf6rq5

However I'm still investigating it (Pango, ttf-dejavu, xfonts-base) are installed and idk why this happens (haven't straced it for further output)

**Comment by xeffyr** [comment]
> ttf-dejavu

Try different font. Here is what I have on my desktop (not proot):
```
fonts-beng
fonts-beng-extra
fonts-crosextra-caladea
fonts-crosextra-carlito
fonts-dejavu
fonts-dejavu-core
fonts-dejavu-extra
fonts-deva
fonts-deva-extra
fonts-droid-fallback
fonts-freefont-ttf
fonts-gargi
fonts-gubbi
fonts-gujr
fonts-gujr-extra
fonts-guru
fonts-guru-extra
fonts-indic
fonts-kacst
fonts-kacst-one
fonts-kalapi
fonts-khmeros-core
fonts-knda
fonts-lao
fonts-liberation
fonts-liberation2
fonts-linuxlibertine
fonts-lklug-sinhala
fonts-lohit-beng-assamese
fonts-lohit-beng-bengali
fonts-lohit-deva
fonts-lohit-gujr
fonts-lohit-guru
fonts-lohit-knda
fonts-lohit-mlym
fonts-lohit-orya
fonts-lohit-taml
fonts-lohit-taml-classical
fonts-lohit-telu
fonts-mlym
fonts-nakula
fonts-navilu
fonts-noto-cjk
fonts-noto-color-emoji
fonts-noto-core
fonts-noto-extra
fonts-noto-mono
fonts-noto-ui-core
fonts-open-sans
fonts-opensymbol
fonts-orya
fonts-orya-extra
fonts-pagul
fonts-sahadeva
fonts-samyak-deva
fonts-samyak-gujr
fonts-samyak-mlym
fonts-samyak-taml
fonts-sarai
fonts-sil-abyssinica
fonts-sil-gentium
fonts-sil-gentium-basic
fonts-sil-padauk
fonts-smc
fonts-smc-anjalioldlipi
fonts-smc-chilanka
fonts-smc-dyuthi
fonts-smc-gayathri
fonts-smc-karumbi
fonts-smc-keraleeyam
fonts-smc-manjari
fonts-smc-meera
fonts-smc-rachana
fonts-smc-raghumalayalamsans
fonts-smc-suruma
fonts-smc-uroob
fonts-taml
fonts-telu
fonts-telu-extra
fonts-thai-tlwg
fonts-tibetan-machine
fonts-tlwg-garuda
fonts-tlwg-garuda-ttf
fonts-tlwg-kinnari
fonts-tlwg-kinnari-ttf
fonts-tlwg-laksaman
fonts-tlwg-laksaman-ttf
fonts-tlwg-loma
fonts-tlwg-loma-ttf
fonts-tlwg-mono
fonts-tlwg-mono-ttf
fonts-tlwg-norasi
fonts-tlwg-norasi-ttf
fonts-tlwg-purisa
fonts-tlwg-purisa-ttf
fonts-tlwg-sawasdee
fonts-tlwg-sawasdee-ttf
fonts-tlwg-typewriter
fonts-tlwg-typewriter-ttf
fonts-tlwg-typist
fonts-tlwg-typist-ttf
fonts-tlwg-typo
fonts-tlwg-typo-ttf
fonts-tlwg-umpush
fonts-tlwg-umpush-ttf
fonts-tlwg-waree
fonts-tlwg-waree-ttf
fonts-ubuntu
fonts-urw-base35
fonts-yrsa-rasa
```

**Comment by WMCB-Tech** [comment]
Ok i found a new output:
```
###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x5C0015,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x5C0015,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x5C0015,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x5C0015,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv
```

It also shows about channel error cannot send/recv

**Comment by xeffyr** [comment]
This is something IPC-related.

**Comment by lypanov** [comment]
This was also reported to Firefox directly at https://bugzilla.mozilla.org/show_bug.cgi?id=1681502.

IMHO if it's hitting Firefox running in Alpine / headless it's most likely not a proot specific issue.

**Comment by WMCB-Tech** [comment]
@lypanov Thanks for the information, until firefox updated, will close this issue

**Comment by WMCB-Tech** [comment]
Firefox 84 is released btw, i haven't tested it on Ubuntu proot, if it works this time. i should close this issue

**Comment by WMCB-Tech** [comment]
Still no luck with Firefox 84, it still crashes

**Comment by michalbednarski** [comment]
Keep issue open, I'm looking into this but since Firefox is large program it might take me some time.

**Comment by michalbednarski** [comment]
For now Firefox can be used with `MOZ_FAKE_NO_SANDBOX=1` env variable set, although I'm still looking for PRoot implementation which will nicely support sandbox.

Firefox (and possibly also Chromium as parts of sandboxing are taken from Chromium) installs own seccomp filter with `SECCOMP_RET_TRAP` for actions for which it wants to run own syscall handler and registers `SIGSYS` signal handler which asks unsandboxed process to perform operation.

PRoot on the other hand when sees `SIGSYS` it considers that to be due to Android enforced policy restricting access to syscalls unused by bionic and performs redirections such as `open(2)` -> `openat(2)` and for syscalls for which it doesn't have special redirection it'll make syscall return `-ENOSYS` without triggering signal. That is what is needed for most cases but in case of Firefox/Chromium sandbox this prevents brokered syscalls from being usable at all.

I think I'll add additional logic which upon detection of browser sandbox will disable most proot `SIGSYS` interceptors, but I don't yet have fully working implementation.

**Comment by WMCB-Tech** [comment]
Using that environment variable makes firefox work again:

![Screenshot_2020-12-21-09-29-56-91.jpg](https://user-images.githubusercontent.com/65075766/102730459-cde99400-436f-11eb-87f6-c155ca40d09c.jpg)

**Comment by 2moe** [comment]
> For now Firefox can be used with `MOZ_FAKE_NO_SANDBOX=1` env variable set, although I'm still looking for PRoot implementation which will nicely support sandbox.

Thank you very much.

**Comment by ZhymabekRoman** [comment]
> For now Firefox can be used with `MOZ_FAKE_NO_SANDBOX=1` env variable set, although I'm still looking for PRoot implementation which will nicely support sandbox.

Thanks, your method perfectly works.

I want will offer the solution of this problem.
1) Install Firefox (not important what edition)
2) Open Firefox and enter the address "about:config"
3) Accept a warning of safety
4) In a search box enter "sandbox"
5) Near the line "media.cubeb.sandbox" press the toggle button that its value became "false", and near the line "security.sandbox.content.level" it is necessary to appropriate value "0"
6) Close and reopen Firefox

My way kills two "hares" - fixes the problem with tabs as well as the problem with sound in Firefox

**Comment by WMCB-Tech** [comment]
It would be much easier if Environment Variable is set, so no need to go to configuration settings,

**Comment by michalbednarski** [comment]
I've pushed experimental support onto `firefoxsandbox` branch, so far only tested on AArch64 (on x86_64 there is additional problem that `SYSCALL_AVOIDER` kills process according to Firefox seccomp policy)

For now this is on branch for further testing, although probably it'll be better to use that instead of users/distros disabling sandboxing)

**Comment by NoNameMan1231** [comment]
if still occur,  just change to chromium. 
HOWTO:https://github.com/ayitsleo/terminaltricks/blob/master/apt-pinning-chromium/README.md

**Comment by Pedro1234-code** [comment]
Install Firefox ESR

**Comment by Yonle** [comment]
Now when using firefox without sandbox enabled, The whole proot environment freezes except the host.

**Comment by layaachmad** [comment]
# Solution:

- Enter about:config in address bar
- Click “Accept the risk and continue”
- Click “Show all”
- Search for sandbox
- Change first two values to false, and change security.sandbox.content.level to 1, exactly as in this picture:

Restart firefox

**Comment by ZhymabekRoman** [comment]
> # Solution:
> * Enter about:config in address bar
> * Click “Accept the risk and continue”
> * Click “Show all”
> * Search for sandbox
> * Change first two values to false, and change security.sandbox.content.level to 1, exactly as in this picture:
> 
> Restart firefox

What is the difference from my method? https://github.com/termux/proot/issues/139#issuecomment-751988264

**Comment by layaachmad** [comment]
> > # Solution:
> > * Enter about:config in address bar
> > * Click “Accept the risk and continue”
> > * Click “Show all”
> > * Search for sandbox
> > * Change first two values to false, and change security.sandbox.content.level to 1, exactly as in this picture:
> > 
> > Restart firefox
> 
> What is the difference from my method? https://github.com/termux/proot/issues/139#issuecomment-751988264

Both
