### ISSUE TITLE
Disk full kde plasma error in new proot again

### ISSUE THREAD

**Issue by Ash-ketchm** [termux/proot#200]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```
kf.config.core: Couldn't write "/home/miney/.config/kglobalshortcutsrc" . Disk full?
kf.config.core: Couldn't write "/home/miney/.config/kwinrc" . Disk full?

**Comment by michalbednarski** [comment]
I've pushed fix and it should soon be available in Termux apt repo as `proot 5.1.107-49`

**Comment by Gumball9** [comment]
> I've pushed fix and it should soon be available in Termux apt repo as `proot 5.1.107-49`

Idk why but `Kf.kio.core: "Could not enter folder tags: /."` still exists for Archlinux (Arch64)
![Screenshot_2021-10-31-09-06-54-89_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/87555282/139566265-1106b343-c275-44fa-9a77-1b48cb0fe848.jpg)
![IMG_20211031_091152](https://user-images.githubusercontent.com/87555282/139566385-4a606f02-855b-4aba-8404-df870ac0d7fc.jpg)

**Comment by WMCB-Tech** [comment]
It's just KIO client can't connect to `tags://` uri, although if it's not problematic or the KDE desktop still works fine then should be ignored

**Comment by Gumball9** [comment]
> It's just KIO client can't connect to `tags://` uri, although if it's not problematic or the KDE desktop still works fine then should be ignored

Yes

**Comment by Puffin-Puffy** [comment]
> I've pushed fix and it should soon be available in Termux apt repo as `proot 5.1.107-49`

Thanks u after this now no more disk full erorr comming Thanks!!

**Comment by kde-yyds** [comment]
try 
balloctl --purge
it works
